/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2026-04-09 06:17:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_2;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction(null, null, null, null);
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction(null, null, null, null);
  _jspx_fnmap_2= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction(null, null, null, null);
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Shopping Cart - TestApp</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            background: #f5f7fb;\n");
      out.write("            color: #1f2937;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            max-width: 1100px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 24px;\n");
      out.write("        }\n");
      out.write("        .grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1.2fr 1fr;\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("        .panel {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 14px;\n");
      out.write("            padding: 20px;\n");
      out.write("            box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08);\n");
      out.write("        }\n");
      out.write("        .products, .cart-table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("        .products th, .products td, .cart-table th, .cart-table td {\n");
      out.write("            border-bottom: 1px solid #e5e7eb;\n");
      out.write("            padding: 12px 10px;\n");
      out.write("            text-align: left;\n");
      out.write("            vertical-align: middle;\n");
      out.write("        }\n");
      out.write("        .products th, .cart-table th {\n");
      out.write("            background: #f8fafc;\n");
      out.write("        }\n");
      out.write("        .btn {\n");
      out.write("            border: 0;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 10px 14px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        .btn-primary { background: #2563eb; color: #fff; }\n");
      out.write("        .btn-secondary { background: #e2e8f0; color: #0f172a; }\n");
      out.write("        .btn-danger { background: #dc2626; color: #fff; }\n");
      out.write("        .qty-input {\n");
      out.write("            width: 72px;\n");
      out.write("            padding: 8px;\n");
      out.write("            border: 1px solid #cbd5e1;\n");
      out.write("            border-radius: 8px;\n");
      out.write("        }\n");
      out.write("        .actions { display: flex; gap: 8px; flex-wrap: wrap; }\n");
      out.write("        .muted { color: #64748b; }\n");
      out.write("        .summary {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 12px;\n");
      out.write("            margin-bottom: 14px;\n");
      out.write("        }\n");
      out.write("        .status {\n");
      out.write("            min-height: 24px;\n");
      out.write("            margin: 12px 0 0;\n");
      out.write("            color: #0f766e;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        .top-links a {\n");
      out.write("            margin-right: 14px;\n");
      out.write("        }\n");
      out.write("        @media (max-width: 900px) {\n");
      out.write("            .grid { grid-template-columns: 1fr; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
 HttpSession userSession = session; 
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h1>Shopping Cart</h1>\n");
      out.write("    <p class=\"muted\">This cart updates through JavaScript calls to a servlet, without full-page refreshes.</p>\n");
      out.write("    <div class=\"top-links\">\n");
      out.write("        <a href=\"secure.jsp\">Back to Secure Page</a>\n");
      out.write("        <a href=\"books\">Books</a>\n");
      out.write("        <a href=\"students\">Students</a>\n");
      out.write("        <a href=\"logout\">Logout</a>\n");
      out.write("    </div>\n");
      out.write("    <p>Logged in as: <strong>");
      out.print( userSession.getAttribute("user") );
      out.write("</strong></p>\n");
      out.write("\n");
      out.write("    <div class=\"grid\">\n");
      out.write("        <div class=\"panel\">\n");
      out.write("            <div class=\"summary\">\n");
      out.write("                <h2>Products</h2>\n");
      out.write("                <button class=\"btn btn-secondary\" onclick=\"reloadCart()\">Refresh Cart State</button>\n");
      out.write("            </div>\n");
      out.write("            <table class=\"products\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Item</th>\n");
      out.write("                        <th>Price</th>\n");
      out.write("                        <th>Quantity</th>\n");
      out.write("                        <th>Action</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody id=\"productRows\"></tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"panel\">\n");
      out.write("            <div class=\"summary\">\n");
      out.write("                <h2>Your Cart</h2>\n");
      out.write("                <button class=\"btn btn-danger\" onclick=\"clearCart()\">Clear Cart</button>\n");
      out.write("            </div>\n");
      out.write("            <table class=\"cart-table\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Item</th>\n");
      out.write("                        <th>Qty</th>\n");
      out.write("                        <th>Line Total</th>\n");
      out.write("                        <th>Action</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody id=\"cartRows\"></tbody>\n");
      out.write("            </table>\n");
      out.write("            <h3>Total: $<span id=\"cartTotal\">0.00</span></h3>\n");
      out.write("            <p>Items in cart: <strong id=\"itemCount\">0</strong></p>\n");
      out.write("            <div id=\"status\" class=\"status\"></div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    const apiUrl = '");
      out.print( request.getContextPath() );
      out.write("/cart-api';\n");
      out.write("    let currentProducts = [];\n");
      out.write("\n");
      out.write("    function money(value) {\n");
      out.write("        return Number(value).toFixed(2);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function setStatus(message, isError = false) {\n");
      out.write("        const status = document.getElementById('status');\n");
      out.write("        status.textContent = message;\n");
      out.write("        status.style.color = isError ? '#b91c1c' : '#0f766e';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function renderProducts(products) {\n");
      out.write("        currentProducts = products;\n");
      out.write("        const rows = products.map(product => `\n");
      out.write("            <tr>\n");
      out.write("                <td><a href=\"product.jsp?productId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${encodeURIComponent(product.id)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${escapeHtml(product.name)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</a></td>\n");
      out.write("                <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${money(product.price)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_2));
      out.write("</td>\n");
      out.write("                <td><input class=\"qty-input\" type=\"number\" min=\"1\" value=\"1\" id=\"qty-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\n");
      out.write("                <td>\n");
      out.write("                    <button class=\"btn btn-primary\" onclick=\"addToCart('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">Add to Cart</button>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        `).join('');\n");
      out.write("        document.getElementById('productRows').innerHTML = rows;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function renderCart(cart) {\n");
      out.write("        const rows = cart.map(item => `\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${escapeHtml(item.name)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</td>\n");
      out.write("                <td>\n");
      out.write("                    <input class=\"qty-input\" type=\"number\" min=\"0\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"cart-qty-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                </td>\n");
      out.write("                <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${money(item.lineTotal)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_2));
      out.write("</td>\n");
      out.write("                <td class=\"actions\">\n");
      out.write("                    <button class=\"btn btn-secondary\" onclick=\"updateCart('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">Update</button>\n");
      out.write("                    <button class=\"btn btn-danger\" onclick=\"removeFromCart('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">Remove</button>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        `).join('');\n");
      out.write("        document.getElementById('cartRows').innerHTML = rows || '<tr><td colspan=\"4\">Your cart is empty.</td></tr>';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    async function loadCart() {\n");
      out.write("        const response = await fetch(apiUrl, { credentials: 'same-origin' });\n");
      out.write("        const data = await response.json();\n");
      out.write("        if (!data.success) {\n");
      out.write("            throw new Error(data.message || 'Failed to load cart');\n");
      out.write("        }\n");
      out.write("        renderProducts(data.products || []);\n");
      out.write("        renderCart(data.cart || []);\n");
      out.write("        document.getElementById('cartTotal').textContent = data.total;\n");
      out.write("        document.getElementById('itemCount').textContent = data.itemCount;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    async function postCart(payload, successMessage) {\n");
      out.write("        const formData = new URLSearchParams(payload);\n");
      out.write("        const response = await fetch(apiUrl, {\n");
      out.write("            method: 'POST',\n");
      out.write("            credentials: 'same-origin',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },\n");
      out.write("            body: formData\n");
      out.write("        });\n");
      out.write("        const data = await response.json();\n");
      out.write("        if (!data.success) {\n");
      out.write("            throw new Error(data.message || 'Cart update failed');\n");
      out.write("        }\n");
      out.write("        renderCart(data.cart || []);\n");
      out.write("        document.getElementById('cartTotal').textContent = data.total;\n");
      out.write("        document.getElementById('itemCount').textContent = data.itemCount;\n");
      out.write("        setStatus(successMessage || 'Cart updated.');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    async function addToCart(productId) {\n");
      out.write("        try {\n");
      out.write("            const qtyField = document.getElementById(`qty-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\n");
      out.write("            const quantity = qtyField ? qtyField.value : 1;\n");
      out.write("            await postCart({ action: 'add', productId, quantity }, 'Item added to cart.');\n");
      out.write("        } catch (error) {\n");
      out.write("            setStatus(error.message, true);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    async function updateCart(productId) {\n");
      out.write("        try {\n");
      out.write("            const qtyField = document.getElementById(`cart-qty-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\n");
      out.write("            const quantity = qtyField ? qtyField.value : 1;\n");
      out.write("            await postCart({ action: 'update', productId, quantity }, 'Cart item updated.');\n");
      out.write("        } catch (error) {\n");
      out.write("            setStatus(error.message, true);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    async function removeFromCart(productId) {\n");
      out.write("        try {\n");
      out.write("            await postCart({ action: 'remove', productId }, 'Item removed from cart.');\n");
      out.write("        } catch (error) {\n");
      out.write("            setStatus(error.message, true);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    async function clearCart() {\n");
      out.write("        try {\n");
      out.write("            await postCart({ action: 'clear' }, 'Cart cleared.');\n");
      out.write("        } catch (error) {\n");
      out.write("            setStatus(error.message, true);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function escapeHtml(value) {\n");
      out.write("        return String(value)\n");
      out.write("            .replace(/&/g, '&amp;')\n");
      out.write("            .replace(/</g, '&lt;')\n");
      out.write("            .replace(/>/g, '&gt;')\n");
      out.write("            .replace(/\"/g, '&quot;')\n");
      out.write("            .replace(/'/g, '&#39;');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    loadCart().catch(error => setStatus(error.message, true));\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
