/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2026-04-09 06:15:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Product Detail - TestApp</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            background: linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%);\n");
      out.write("            color: #1f2937;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            max-width: 900px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 28px;\n");
      out.write("        }\n");
      out.write("        .card {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 18px;\n");
      out.write("            box-shadow: 0 18px 40px rgba(15, 23, 42, 0.10);\n");
      out.write("            padding: 28px;\n");
      out.write("        }\n");
      out.write("        .muted { color: #64748b; }\n");
      out.write("        .price {\n");
      out.write("            font-size: 2rem;\n");
      out.write("            font-weight: 800;\n");
      out.write("            color: #0f172a;\n");
      out.write("            margin: 8px 0 18px;\n");
      out.write("        }\n");
      out.write("        .controls {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 12px;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .qty-input {\n");
      out.write("            width: 86px;\n");
      out.write("            padding: 10px;\n");
      out.write("            border: 1px solid #cbd5e1;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            font-size: 1rem;\n");
      out.write("        }\n");
      out.write("        .btn {\n");
      out.write("            border: 0;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        .btn-primary { background: #2563eb; color: #fff; }\n");
      out.write("        .btn-secondary { background: #e2e8f0; color: #0f172a; }\n");
      out.write("        .meta {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(2, minmax(0, 1fr));\n");
      out.write("            gap: 12px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .meta div {\n");
      out.write("            background: #f8fafc;\n");
      out.write("            border-radius: 14px;\n");
      out.write("            padding: 14px;\n");
      out.write("        }\n");
      out.write("        .status {\n");
      out.write("            margin-top: 16px;\n");
      out.write("            min-height: 24px;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        a { color: #2563eb; text-decoration: none; }\n");
      out.write("        @media (max-width: 700px) {\n");
      out.write("            .meta { grid-template-columns: 1fr; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
 HttpSession userSession = session; 
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <p><a href=\"cart.jsp\">Back to Cart</a> | <a href=\"secure.jsp\">Secure Page</a> | <a href=\"logout\">Logout</a></p>\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <p class=\"muted\">Logged in as: <strong>");
      out.print( userSession.getAttribute("user") );
      out.write("</strong></p>\n");
      out.write("        <h1 id=\"productName\">Loading product...</h1>\n");
      out.write("        <div class=\"price\" id=\"productPrice\"></div>\n");
      out.write("        <p id=\"productDescription\" class=\"muted\"></p>\n");
      out.write("\n");
      out.write("        <div class=\"meta\">\n");
      out.write("            <div>\n");
      out.write("                <strong>Product ID</strong>\n");
      out.write("                <div id=\"productIdValue\">-</div>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <strong>Category</strong>\n");
      out.write("                <div>Shopping cart demo</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"controls\">\n");
      out.write("            <label for=\"quantity\"><strong>Quantity:</strong></label>\n");
      out.write("            <input id=\"quantity\" class=\"qty-input\" type=\"number\" min=\"1\" value=\"1\">\n");
      out.write("            <button class=\"btn btn-primary\" onclick=\"addToCart()\">Add to Cart</button>\n");
      out.write("            <button class=\"btn btn-secondary\" onclick=\"goToCart()\">Go to Cart</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"status\" class=\"status\"></div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    const apiUrl = '");
      out.print( request.getContextPath() );
      out.write("/cart-api';\n");
      out.write("    const selectedProductId = new URLSearchParams(window.location.search).get('productId') || 'P1001';\n");
      out.write("    let selectedProduct = null;\n");
      out.write("\n");
      out.write("    function money(value) {\n");
      out.write("        return Number(value).toFixed(2);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function setStatus(message, isError = false) {\n");
      out.write("        const status = document.getElementById('status');\n");
      out.write("        status.textContent = message;\n");
      out.write("        status.style.color = isError ? '#b91c1c' : '#0f766e';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function escapeHtml(value) {\n");
      out.write("        return String(value)\n");
      out.write("            .replace(/&/g, '&amp;')\n");
      out.write("            .replace(/</g, '&lt;')\n");
      out.write("            .replace(/>/g, '&gt;')\n");
      out.write("            .replace(/\"/g, '&quot;')\n");
      out.write("            .replace(/'/g, '&#39;');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    async function loadProduct() {\n");
      out.write("        const response = await fetch(apiUrl, { credentials: 'same-origin' });\n");
      out.write("        const data = await response.json();\n");
      out.write("        if (!data.success) {\n");
      out.write("            throw new Error(data.message || 'Unable to load product catalog');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        selectedProduct = (data.products || []).find(product => product.id === selectedProductId) || (data.products || [])[0];\n");
      out.write("        if (!selectedProduct) {\n");
      out.write("            throw new Error('Product not found');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        document.getElementById('productName').textContent = selectedProduct.name;\n");
      out.write("        document.getElementById('productPrice').textContent = '$' + money(selectedProduct.price);\n");
      out.write("        document.getElementById('productDescription').textContent = 'This item can be added to your session cart without a page refresh.';\n");
      out.write("        document.getElementById('productIdValue').textContent = selectedProduct.id;\n");
      out.write("        setStatus('Product loaded.');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    async function addToCart() {\n");
      out.write("        try {\n");
      out.write("            const quantity = document.getElementById('quantity').value || 1;\n");
      out.write("            const formData = new URLSearchParams({ action: 'add', productId: selectedProduct.id, quantity });\n");
      out.write("            const response = await fetch(apiUrl, {\n");
      out.write("                method: 'POST',\n");
      out.write("                credentials: 'same-origin',\n");
      out.write("                headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },\n");
      out.write("                body: formData\n");
      out.write("            });\n");
      out.write("            const data = await response.json();\n");
      out.write("            if (!data.success) {\n");
      out.write("                throw new Error(data.message || 'Cart update failed');\n");
      out.write("            }\n");
      out.write("            setStatus(escapeHtml(selectedProduct.name) + ' added to cart.');\n");
      out.write("        } catch (error) {\n");
      out.write("            setStatus(error.message, true);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function goToCart() {\n");
      out.write("        window.location.href = 'cart.jsp';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    loadProduct().catch(error => setStatus(error.message, true));\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
